root = "/home/suda/.local/share/containerd"
state = "/run/user/1001/containerd"

[grpc]
  address = "/run/user/1001/containerd/containerd.sock"

[plugins]
  [plugins.cri]
    restrict_oom_score_adj = true
    disable_apparmor = true
    [plugins.cri.containerd]
      [plugins.cri.containerd.runtimes]
        [plugins.cri.containerd.runtimes.crun-sd]
          runtime_type = "io.containerd.runc.v2"
          [plugins.cri.containerd.runtimes.crun-sd.options]
            BinaryName = "/usr/local/bin/crun"
            SystemdCgroup = true
        [plugins.cri.containerd.runtimes.runc-sd]
          runtime_type = "io.containerd.runc.v2"
          [plugins.cri.containerd.runtimes.runc-sd.options]
            BinaryName = "/usr/local/sbin/runc"
            SystemdCgroup = true
